### ISSUE TITLE
The pre-trained model

### ISSUE THREAD

**Issue by LaLaLailalai** [garvita-tiwari/PoseNDF#1]
Hi @garvita-tiwari ,

Thanks for your great work!  When will you upload the pre-trained model? Since the link is with no file. I really like to see more results based on the pretrained model, thank you.

**Comment by APeiZou** [comment]
@garvita-tiwari ,   hello,  I also need the pretrained model, thank you.

**Comment by garvita-tiwari** [comment]
Hi, please find the pretrained model in the nextcloud link. It's updated.
