### ISSUE TITLE
Difficulties for training the network

### ISSUE THREAD

**Issue by daidedou** [garvita-tiwari/PoseNDF#10]
Hi to all authors of the paper, I wish you a happy new year.

I've been trying to use PoseNDF in order to denoise some poses, but I encountered a few problems in attempting to reproduce the experiments.
-First, the pretrained network is not in the right format. It seems that it is a 3D convolution encoder, but not the one described in the paper.
-The sigmas parameters from config/amass.yaml are not used. I believe they refer to the different noise levels in training data but I don't know how to use them
-I'm not sure about how the .npz are generated. Do you generate one per sequence of motion or one per sub-dataset of AMASS? Because  the batch size is set to 1000, which gives very big batches in the second case.

Anyway, I think that uploading the pre-trained network would be enough for me. I hope it is possible for you.
Thank you in advance for your answer!

**Comment by garvita-tiwari** [comment]
> Hi to all authors of the paper, I wish you a happy new year.
> 
> I've been trying to use PoseNDF in order to denoise some poses, but I encountered a few problems in attempting to reproduce the experiments. -First, the pretrained network is not in the right format. It seems that it is a 3D convolution encoder, but not the one described in the paper. -The sigmas parameters from config/amass.yaml are not used. I believe they refer to the different noise levels in training data but I don't know how to use them -I'm not sure about how the .npz are generated. Do you generate one per sequence of motion or one per sub-dataset of AMASS? Because the batch size is set to 1000, which gives very big batches in the second case.

Please update the code and try with the latest uploaded model. Regarding the sigmas in config file, you can ignore them for inference/generation. If you which to train the model, then you can follow the data preparation step, as mentioned in README.md. Each .npz file corresponds to 500k sampled poses(noisy and clean poses) and corresponding distance from AMASS dataset. These noisy samples were created by adding noise to AMASS sequences.  So e.g. MPI_Limits/03990.npz file will contain poses that were generated by adding noise to poses from  MPI_Limits/03990 sequence. During training we pick 50k(num_pts) pose from each of these files and we take a batch of such points (check models/load_data.py). 
> 
> Anyway, I think that uploading the pre-trained network would be enough for me. I hope it is possible for you. Thank you in advance for your answer!

Please check the link: https://nextcloud.mpi-klsb.mpg.de/index.php/s/4zxN93WL769pSAK
