### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by tommyshelby4** [garvita-tiwari/PoseNDF#12]
Can somebody help with the configuration file regarding pose generation in test mode? I created a DFNet entry but I set the input_dims and dims with random numbers. If somebody could help, I would be grateful.

**Comment by garvita-tiwari** [comment]
please check the updated config file : https://github.com/garvita-tiwari/PoseNDF/commit/4b8f1f02d03797a7eac7388c7ebad905bb4df591
