### ISSUE TITLE
Data Preparation

### ISSUE THREAD

**Issue by tommyshelby4** [garvita-tiwari/PoseNDF#13]
I get an error when trying to load the data for inference. 
![image](https://user-images.githubusercontent.com/36934521/215718785-7885efe1-3d1c-43cb-bd1b-aa4786434609.png)
![image](https://user-images.githubusercontent.com/36934521/215718575-f3d16b21-319f-4b00-a49c-6db5365ecf03.png)
When I debug it, I see it's totally normal as the .npz files do not contain any 'dist' or 'nn_pose' key entries. I took a look at the data preparation scripts and I cannot see in which way they could be solving this issue. Can anybody who has managed to run the code properly help me go all the way?

**Comment by HospitableHost** [comment]
you need to take a look at the file 'prepare_data.py' and 'prepare_traindata.py'.

**Comment by tommyshelby4** [comment]
I have taken a look but I keep getting errors like that:
![image](https://user-images.githubusercontent.com/36934521/216013507-f6b93950-b1bf-455b-9823-b1a8ca6a11ae.png)
Do you have any idea?

**Comment by HospitableHost** [comment]
> I have taken a look but I keep getting errors like that: ![image](https://user-images.githubusercontent.com/36934521/216013507-f6b93950-b1bf-455b-9823-b1a8ca6a11ae.png) Do you have any idea?

why ( _, 21 , 3 )? Is't ( _, 21 , 4 )?

**Comment by tommyshelby4** [comment]
Why should it be 4?

**Comment by garvita-tiwari** [comment]
> > I have taken a look but I keep getting errors like that: ![image](https://user-images.githubusercontent.com/36934521/216013507-f6b93950-b1bf-455b-9823-b1a8ca6a11ae.png) Do you have any idea?
> 
> why ( _, 21 , 3 )? Is't ( _, 21 , 4 )?

It is 3 here, because we are loading AMASS poses, in axis angle representation(not quaternion).

**Comment by garvita-tiwari** [comment]
> I have taken a look but I keep getting errors like that: ![image](https://user-images.githubusercontent.com/36934521/216013507-f6b93950-b1bf-455b-9823-b1a8ca6a11ae.png) Do you have any idea?

This looks like that 
1. either you are using a different no. of joints
2. or you are loading a data, which was saved differently.

Did you run sample_poses.py before running prepare_data.py?? 
Please share the shape of pose_seq after this line: 
pose_seq = np.load(os.path.join(ds_dir, seq))['pose_body']

**Comment by tommyshelby4** [comment]
Thanks for your reply. I haven't run sample_poses.py because I get this error while the PoseNDF env is activated
![image](https://user-images.githubusercontent.com/36934521/216649173-e3cdb7a4-d398-43d5-8c1e-0b224ccc5a7a.png)

**Comment by garvita-tiwari** [comment]
> Thanks for your reply. I haven't run sample_poses.py because I get this error while the PoseNDF env is activated ![image](https://user-images.githubusercontent.com/36934521/216649173-e3cdb7a4-d398-43d5-8c1e-0b224ccc5a7a.png)

This error has nothing to do with the environment. There is file data/data_splits.py which basically contains the AMASS train/val/test split.  "from data.data_splits import amass_splits" access this.

I guess this is because of path.  Try changing "from data.data_splits import amass_splits" to "from data_splits import amass_splits"
