### ISSUE TITLE
Bug in create_data.py

### ISSUE THREAD

**Issue by Alan-LanFeng** [garvita-tiwari/PoseNDF#15]
https://github.com/garvita-tiwari/PoseNDF/blob/4b8f1f02d03797a7eac7388c7ebad905bb4df591/data/create_data.py#L79-L80

I think there's something wrong with the code snippet. The two lines of code will not add any noise to the data.

**Comment by garvita-tiwari** [comment]
L79: Adds noise to poses(in quaternion)
L80: normalizes the pose

**Comment by Alan-LanFeng** [comment]
Thanks for answering. But the sigma here is a float such as 0.01. If I understood correctly, what the code does is just multiplying sample_pose by 1.01 then normalize it.

**Comment by garvita-tiwari** [comment]
Hi,
Thanks for pointing this out. 
It should be : sampled_pose +sigma*np.random.rand(21,4)*sampled_pose
