### ISSUE TITLE
about noisy motion in denoise exp

### ISSUE THREAD

**Issue by felix-ky** [garvita-tiwari/PoseNDF#17]
Hi, could you upload your code thta processing the data to get noisy motion in denoise experiment? 
Gaussian noise is added to quanternion or rotvec?

**Comment by garvita-tiwari** [comment]
Hi, I have used the data preparation code of humor. But instead of adding noise to joint location, I add noise to rotvec.

Specifically the noise added here: https://github.com/davrempe/humor/blob/main/humor/datasets/amass_fit_dataset.py#L122

is changed to: 
 
        if self.noise_std > 0.0:
            cur_bm = self.male_bm_GT
            observed_dict['pose_body'] += torch.randn_like(observed_dict['pose_body']) * self.noise_std

**Comment by felix-ky** [comment]
Thanks a lot!

**Comment by felix-ky** [comment]
By the way,  what's the value of noise_std? and noise is only added to 21 joints(excluded root and left/right hand)?

**Comment by garvita-tiwari** [comment]
1.  We create samples by using noise_std = 0.1 and 0.5
2. Yes, we only add noise to 21 joints

**Comment by felix-ky** [comment]
Many Thanks！

**Comment by felix-ky** [comment]
Hi, I have found that the evaluating metric of denoise exp is computing mpve between noisy verts and denoised one in [here](https://github.com/garvita-tiwari/PoseNDF/blob/main/experiments/motion_denoise.py#L114). 
Are all results in denoise exp(Table 1) are computed in this way? and why not choose to compute the mpve between gt verts and denoised verts as [humor did](https://github.com/davrempe/humor/blob/main/humor/fitting/eval_fitting_3d.py#L246) 
And  I found sometimes the mpve between denoised verts and gt verts is bigger than between noisy verts and gt verts.

**Comment by garvita-tiwari** [comment]
> 

mpve is calculated using distance between gt and denoised .
If you are using current model, then you might get wrong numbers, as the model is not optmial.
