### ISSUE TITLE
Update doc 

### ISSUE THREAD

**Issue by leobxpan** [garvita-tiwari/PoseNDF#2]
Thanks for the great work. The doc accompanying the code seems to be super outdated. Could you please update the instructions on environment, training / testing, and pre-trained models? That'd be very helpful.

**Comment by leobxpan** [comment]
`model/loss_utils.py` seems to be missing too.

**Comment by garvita-tiwari** [comment]
I have updated the installation file with requirements and also updated the pretrained model. Please check the updated repo.
