### ISSUE TITLE
posendf's forward function self.model_occ

### ISSUE THREAD

**Issue by 2019EPWL** [garvita-tiwari/PoseNDF#3]
hi, in the posendf.py there is a `dist_pred = self.model_occ(rand_pose.reshape(self.batch_size,84))`, but I can't find the definition of self.model_occ in the repo， could you help with it?

**Comment by rczDS** [comment]
i've got the similar quetion, in posendf.py:
`self.dfnet = DFNet(opt['model']['DFNet']).to(self.device))`
`dist_pred = self.dfnet(rand_pose_in.reshape(self.batch_size,84))`
but in default amass.yaml, "DFNet" is not defined under "model".  anybody knows the params?

**Comment by HospitableHost** [comment]
Besides, the pretrained model is very strange, 1. why it has conv layers? 2. it has no dfnet parameters 3. it has no StructureEncoder parameters. (I change the model.CanSDF to model.DFNet and model.StrEnc.use to True)
![1](https://user-images.githubusercontent.com/44576391/208251930-31c48f7c-f468-435d-a186-792f9388a6a8.png)
![2](https://user-images.githubusercontent.com/44576391/208251934-390aff18-3185-4a43-8ae7-d044a114d219.png)

**Comment by felix-ky** [comment]
same problem

**Comment by garvita-tiwari** [comment]
please use the latest commit with updated config file: https://github.com/garvita-tiwari/PoseNDF/commit/4b8f1f02d03797a7eac7388c7ebad905bb4df591
