### ISSUE TITLE
Question about the role of nn_pose

### ISSUE THREAD

**Issue by tianxintao** [garvita-tiwari/PoseNDF#30]
Dear authors,

Thank you for your amazing work.

I am having some questions about the poses acquired by querying KNN as you mentioned in the supplementary material. I can see the KNN process is implemented in the `prepare_traindata.py`, and the resulting poses are saved as `nn_pose` in the npz file.

But in the dataloader (`load_data.py`), this line `# nn_pose = pose_data['nn_pose'][subsample_indices]` indicates `nn_pose` is not used in training. So I'm confused what role the KNN process plays in the training.

Looking forward to your reply! Thanks again.

**Comment by YZ-Shiao** [comment]
From my point of view, only 'dist' and 'pose' are useful for trian, but 'nn_pose' can be used for debug. For example, you can visualize some poses and their nn_pose to check whether they are close.

**Comment by tianxintao** [comment]
Thanks for the explanation, that makes sense.
