### ISSUE TITLE
Dependencies installation

### ISSUE THREAD

**Issue by tommyshelby4** [garvita-tiwari/PoseNDF#5]
I am trying to solve the conda environment and I get this error:
![image](https://user-images.githubusercontent.com/36934521/208098463-14922b93-66c3-47ce-ae46-259d9ed24573.png)
Any ideas?

**Comment by tommyshelby4** [comment]
Is there anynody who has successfully completed the environment setup who can provide me with their conda version number?

**Comment by garvita-tiwari** [comment]
I am using : conda 4.8.3
If you requirements.txt file doesn't work for you .
You can also install the following libraries using pip.
 pip install trimesh scipy smplx

for pytorch3d: https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md

**Comment by tommyshelby4** [comment]
So I totally skip the conda environment and just install dependencies with pip? I have also tried this but I have an issue with ps-bodymesh0.3 which pip does not seem to find. Could you provide any assistance on this??????

**Comment by tommyshelby4** [comment]
Any suggestions?

**Comment by garvita-tiwari** [comment]
The current version of code will work without ps-bodymesh library. So you don't need to install it.
Thanks for pointing out. I will update the requirements.txt

**Comment by tommyshelby4** [comment]
Thank you very much for your responses!

**Comment by atodniAr** [comment]
> I am using : conda 4.8.3 If you requirements.txt file doesn't work for you . You can also install the following libraries using pip. pip install trimesh scipy smplx
> 
> for pytorch3d: https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md

I followed this @garvita-tiwari . When I run `conda install pytorch3d=0.5.0 -c pytorch3d` I got:

```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pytorch3d=0.5.0 -> python[version='>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.5,<3.6.0a0']
```

Now it seems conflict with python=3.8.12 stated in requirements.txt

**Comment by garvita-tiwari** [comment]
> > I am using : conda 4.8.3 If you requirements.txt file doesn't work for you . You can also install the following libraries using pip. pip install trimesh scipy smplx
> > for pytorch3d: https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md
> 
> I followed this @garvita-tiwari . When I run `conda install pytorch3d=0.5.0 -c pytorch3d` I got:
> 
> ```
> UnsatisfiableError: The following specifications were found
> to be incompatible with the existing python installation in your environment:
> 
> Specifications:
> 
>   - pytorch3d=0.5.0 -> python[version='>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.5,<3.6.0a0']
> ```
> 
> Now it seems conflict with python=3.8.12 stated in requirements.txt

I have updated requirement.txt and INSTALL instruction, so that it is compatible with new pytorch3d version. This new environment is tested with python3.9.  Please follow the steps in INSTALL.MD.
