### ISSUE TITLE
Pretrained model 

### ISSUE THREAD

**Issue by tommyshelby4** [garvita-tiwari/PoseNDF#8]
Pretrained model file checkpoint_latest.tar cannot be uncompressed using tar or gzip in Ubuntu. Does anybody have the same problem with me?

**Comment by HospitableHost** [comment]
It does not need to be decompressed as it is a format for checkpoints.

**Comment by KyunHwan** [comment]
I know this is closed, but for those like me that stumbled upon this thread, info on this page might help decipher what "format for checkpoints" means:
[https://pytorch.org/tutorials/beginner/saving_loading_models.html?highlight=pth%20tar](url)
